Refactor: Add guard clauses to improve readability.

diff --git a/bin/ssh-agent-kick b/bin/ssh-agent-kick
--- a/bin/ssh-agent-kick
+++ b/bin/ssh-agent-kick
@@ -7,10 +7,27 @@
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 ssh_agent_kick () {
-  local old_level=${LOG_LEVEL}
-  LOG_LEVEL=${LOG_LEVEL_NOTICE}
   # Note that EUID is a Bash-ism. Check nonzero ID,
   # i.e., insist that user is not root.
+  if [ $(id -u) -eq 0 ]; then
+    >&2 echo "ERROR: Please try again as not root."
+    return 1
+  fi
+  # 2020-03-18: (lb): I do not recall why checking TERM matters. Adding
+  # ERROR message, so I'll at least know if/when this'd be called.
+  if [ "${TERM}" = "dumb" ]; then
+    >&2 echo "ERROR: Not an appropriate context: TERM too dumb."
+    return 1
+  fi
+  # Pretty obvi. No .ssh/: nothing to do.
+  if [ ! -e "${HOME}/.ssh" ]; then
+    >&2 echo "ERROR: User's ~/.ssh not online; nothing to kick!"
+    return 1
+  fi
+  # Not we made it!
+
+  local old_level=${LOG_LEVEL}
+  LOG_LEVEL=${LOG_LEVEL_NOTICE}
   if [ $(id -u) -ne 0 ] &&
      [ "dumb" != "${TERM}" ] &&
      [ -e "${HOME}/.ssh" ]
