Deps: Update faithfuls <sh-rm_safe>
- Source: sh-rm_safe @ fcaeb61ceadc [1.2.0 at HEAD “fcaeb61”]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/DepoXy/depoxy/blob/release/home/.kit/git/ohmyrepos/lib/my-deps-manage-shoilerplate.sh

diff --git a/deps/sh-rm_safe/bin/rm_rotate b/deps/sh-rm_safe/bin/rm_rotate
--- a/deps/sh-rm_safe/bin/rm_rotate
+++ b/deps/sh-rm_safe/bin/rm_rotate
@@ -3,38 +3,156 @@
 # Project: https://github.com/landonb/sh-rm_safe#🗑
 # License: MIT
 
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
 RM_SAFE_TRASH_HOME="${RM_SAFE_TRASH_HOME:-${HOME}}"
 
+# USYNC: In lieu of sourcing a common lib file, keep
+#        the RM_SAFE_FIRST_TRASH environ synced. See:
+#           ~/.kit/sh/sh-rm_safe/bin/rm_safe
+#           ~/.kit/sh/sh-rm_safe/bin/rm_rotate
+set_environs () {
+  if ! os_is_macos; then
+    RM_SAFE_FIRST_TRASH="${RM_SAFE_FIRST_TRASH:-.trash0}"
+    RM_SAFE_FINAL_TRASH="${RM_SAFE_FINAL_TRASH:-.trash}"
+  else
+    RM_SAFE_FIRST_TRASH="${RM_SAFE_FIRST_TRASH:-.Trash0}"
+    RM_SAFE_FINAL_TRASH="${RM_SAFE_FINAL_TRASH:-.Trash}"
+  fi
+}
+
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-echo_boxy=false
+# USAGE: Call rm_rotate to (finally) delete previoused trashed paths.
+# - rm_safe moves paths to an intermediate trash directory.
+# - rm_rotate then moves paths from the intermediate trash
+#   to a final trash directory.
+#   - rm_rotate empties the final trash directory first.
+# This is a just-in-case approach to removing files.
+# - E.g., suppose you remove a path, then later realize you didn't
+#   mean it. Because it was "safely" removed, you can dig it out
+#   of the trash.
+# - Adding an intermediate trash directory adds an additional
+#   just-in-case safety layer: Call rm_rotate occassionally to
+#   cleanup previously "deleted" files, but realize you have to
+#   call it *twice* to truly eradicate them.
+#   - I.e., call `rm_safe` to move a path to the intermediate
+#     trash. Then call `rm_rotate` to move intermediate trash
+#     paths to the final trash. Then call `rm_rotate` again to
+#     empty the final trash.
+# - In this manner, you can call rm_rotate periodically, e.g.,
+#   once a month or whatever, and you should't have to worry
+#   about accidentally deleting things.
+#
+# SAVVY: You could add a cron/anacron/launchd job to check the
+#        timestamp of the intermediate trash, and to call
+#        `rm_rotate` after a certain amount of time has elapsed.
+#        - E.g., call `rm_rotate` weekly, then you're assured
+#          that when you `rm_safe` something, it'll still be
+#          recoverable 1-2 weeks later. Probably enough time
+#          to realize if you removed something erroneously.
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-# 2016-04-26: I added rm_rotate because, while trashes were being
-# created on different devices from rm_safe, rmtrash was only emptying
-# the trash in the user's home.
-#   Also: I find myself feeling more comfortable moving .trash to .trash-TBD
-#   for a while and then deleting the .trash-TBD, just in case I don't, say,
-#   in a week realize I deleted something. So here's a two-step trash:
-#   if you call rmtrash once, it'll temporarily backup the .trash dirs;
-#   when you call rmtrash again, it'll remove the last temporary backups.
-#   In this manner, you can call rmtrash periodically, like once a month
-#   or whatever, and you won't have to worry about accidentally deleting
-#   things.
-#   MAYBE: You could do an anacron check on the timestamp of the .trash-TBD
-#          and call rm_rotate after a certain amount of time has elapsed.
+# SAVVY/2024-07-12: Read on for why ~/.Trash0 is now the first trash
+#                   destination, because macOS:
+#
+# - This project, 10-yrs strong on Linux, has adapted itself for the
+#   macOS Trash.
+# - These rules now apply, because macOS:
+#   - The first "trash" location is a directory that other apps
+#     should not care about: ~/.Trash-TBD
+#   - The second "trash" location (once you rotate) is the normal
+#     macOS Trash: ~/.Trash
+#     - This is logically the same path this project has used on Linux
+#       for-ever, ~/.trash, because macOS uses a case-insensitive file
+#       system.
+#
+# DEETS: The author has used `rm_safe` for almost a decade on Linux, and
+#        only recently, moving to macOS, did I realize its preferred 
+#        ~/.trash location conflicts with the (honorable) macOS
+#        ~/.Trash directory (because macOS uses a case-insensitive
+#        file system for the main APFS Volume, these two paths are
+#        logically the same).
+# Furthermore:
+# - On @macOS, ~/.Trash has special permissions via ACL (Access Control
+#   Lists), and the directory cannot be renamed or moved.
+#   - Nor can apps (including terminal apps) read its contents without
+#     Full Disk Access permissions.
+#   - You can see the specific permissions with Apple's `ls` command
+#     (but not with Homebrew's (GNU) `ls`):
+#       $ /bin/ls -le -d ~/.Trash
+#       drwx------+ 207 user  staff  6624 Jul  8 21:58 /Users/user/.Trash
+#        0: group:everyone deny delete
+# - One option is to continue using the same trash name this command
+#   has used for years, albeit capitalized, e.g.,:
+#     os_is_macos && trash_name='.Trash'
+#   and to move individual paths out of it on rotation (e.g.,
+#   `mv ~/.Trash/* ~/.Trash-TDB`), rather than simply renaming the
+#   directory (`mv ~/.Trash ~/.Trash-TBD`) which macOS disallows.
+#   - But then rotated files are no longer protected like files in the
+#     honorable ~/.Trash.
+# - But does ACL on the ~/.Trash really matter?
+#   - If data being deleted is really that precious, won't the user
+#     `rm -rf` (or `rmrm`) the path instead of ~/.trash'ing it?
+#   - Also, why does a "deleted" file become *more* restricted when
+#     the user deletes it? (I.e., if Full Disk Access isn't needed to
+#     access a file in the user's home directory, why then when it's
+#     "deleted" (moved to ~/.Trash) does is suddenly gain extra-
+#     ordinary powers, er, access permissions?)
+# - In any case, from the author's time on Linux, I wouldn't expect
+#   my file trash to be as secure as Apple makes it.
+#   - Srsly, use `command rm -rf` if you're *that* worried.
+#     - (Which makes me ask: What is Apple worried about that's
+#       gonna access your trash? As a Dev, if you're already
+#       installing Brew apps and going to System Settings to
+#       tell macOS to not care that an app is unsigned... like,
+#       where are we here? Either I trust all that's running on my
+#       machine, or I'm a complete fool and some hacker or
+#       nation-state is spying on my right now as I type this, Gosh!)
+#   - Which also means I don't feel strongly one way or another which
+#     approach to take.
+#     - Also note what `rm_rotate` does: It maintains *two* trash
+#       directories. So if one is macOS's ~/.Trash, and one isn't,
+#       then one trash has enhanced ACL permissions, and one doesn't.
+#     - So it makes sense to use ~/.Trash as the final destination,
+#       and to use ~/.Trash0 (or whatever) as the first destination.
+#
+# Just remember:
+# - When you `rm_safe` a path, it goes to the preliminary ~/.Trash0
+# - When you `rm_rotate`, it empties ~/.Trash, and then ~/.Trash0
+#   files are moved to ~/.Trash
+# - Whatever terminal app you use on @macOS, it must have the
+#   Full Disk Access permission to view the ~/.Trash directory
+
+DRY_RUN=""
+# Uncomment for trace with rotate:
+#  DRY_RUN="echo"
 
 rm_rotate () {
-  local trash_name='.trash'
-  os_is_macos && trash_name='.Trash'
+  local first_trash="${RM_SAFE_FIRST_TRASH}"
+  local final_trash="${RM_SAFE_FINAL_TRASH}"
+
+  _rm_rotate_acl_can_delete_directory () {
+    local test_path="$1"
+
+    # Check @macOS ACL permissions using Apple ls's -e, e.g.,
+    #   $ /bin/ls -le -d ~/.Trash
+    #   drwx------+ 207 user  staff  6624 Jul  8 21:58 /Users/user/.Trash
+    #    0: group:everyone deny delete
+    # - Note also the '+' after flags to indicate ACL perms.
+    ! ( \
+      /bin/ls -le -d "${test_path}" 2> /dev/null \
+        | grep -q -e "group:everyone deny delete"
+      )
+  }
 
   _rm_rotate_enumerate_devices () {
     if command -v findmnt > /dev/null; then
-      local device_path=''
+      local device_path=""
       for device_path in $( \
         findmnt -l -t fuse.gocryptfs,fuse.encfs,ext4 -o TARGET --noheadings \
-          | grep -v '^/boot' \
+          | grep -v "^/boot" \
           | sort \
       ); do
         _rm_rotate_rotate_device_trash "${device_path}"
@@ -48,63 +166,79 @@ rm_rotate () {
   _rm_rotate_rotate_device_trash () {
     local device_path="$1"
 
-    local trash_path="${device_path}/${trash_name}"
-    [ "${device_path}" = "/" ] &&
-      trash_path="${RM_SAFE_TRASH_HOME}/${trash_name}"
+    local first_path
+    local final_path
 
-    if [ ! -d "${trash_path}" ]; then
-      echo "Skip! No trash at ‘${trash_path}’"
+    if [ "${device_path}" = "/" ]; then
+      first_path="${RM_SAFE_TRASH_HOME}/${first_trash}"
+      final_path="${RM_SAFE_TRASH_HOME}/${final_trash}"
+    else
+      first_path="${device_path}/${first_trash}"
+      final_path="${device_path}/${final_trash}"
+    fi
+
+    if [ ! -d "${final_path}" ]; then
+      echo "Skip! No trash at ‘${final_path}’"
 
       return 0
     fi
 
-    local to_be_deleted="${trash_path}-TBD"
-
     local yes_or_no=""
-    printf %s "Empty all items from trash at ‘${trash_path}’? [y/n] "
-    read -e yes_or_no
+    printf %s "Empty ‘${final_path}’, and replace with trash from ‘${first_path}’? [y/n] "
+    read yes_or_no
 
     # Bash-specific: [ "${yes_or_no^^}" = "Y" ]. POSIX-compatible:
-    if [ "$(first_char_capped ${yes_or_no})" != 'Y' ]; then
+    if [ "$(first_char_capped ${yes_or_no})" != "Y" ]; then
       [ -z "${yes_or_no}" ] && echo
-      echo "Skip! User said not to empty ‘${trash_path}’"
+      echo "Skip! User said not to empty ‘${first_path}’"
 
       return 0
+    fi
+
+    local trash_is_deletable=true
+    if ! _rm_rotate_acl_can_delete_directory "${first_path}"; then
+      trash_is_deletable=false
+    fi
+
+    local rotate_is_deletable=true
+    if ! _rm_rotate_acl_can_delete_directory "${final_path}"; then
+      rotate_is_deletable=false
     fi
 
     # Remove the TBD directory from last time.
     # - Note that rm_rotate is not time-based or anything: It rotates
-    #   only when user runs `rmtrash`. That is, it doesn't keep files
+    #   only when user runs `rm_rotate`. That is, it doesn't keep files
     #   for some set amount of time or anything; it keeps files until
-    #   the user runs `rmtrash`, then it deletes the former directory
+    #   the user runs `rm_rotate`, then it deletes the former directory
     #   and moves the active trash to the TBD position. Thus, if user
     #   wants to really permantently remove what's in the trash, they
     #   run rm_trash twice in a row.
-    if [ -d "${to_be_deleted}" ]; then
-      command rm -rf -- "${to_be_deleted}"
+    if [ -d "${final_path}" ]; then
+      # Check @macOS ACL permissions using Apple ls's -e, e.g.,
+      #   $ /bin/ls -le -d ~/.Trash
+      #   drwx------+ 207 user  staff  6624 Jul  8 21:58 /Users/user/.Trash
+      #    0: group:everyone deny delete
+      if ${rotate_is_deletable}; then
+        ${DRY_RUN} command rm -rf -- "${final_path}"
+      else
+        # I.e., ~/.Trash
+        ${DRY_RUN} command rm -rf -- "${final_path}"/*
+      fi
     fi
 
     # Avoid creating -TBD directory if trash already empty.
-    if [ -n "$(command ls -- "${trash_path}")" ]; then
-      # Trash not empty. Move to TBD position (will be deleted on next
-      # rm_rotate), and then create a new trash directory.
+    if [ -n "$(command ls -- "${first_path}")" ]; then
+      # First trash not empty. Move to final directory (which will be
+      # deleted on next rm_rotate), and then create a new first directory.
 
-      # BWARE: macOS ~/.Trash is protected, so cannot rename it.
-      # - INERT: Ideally, this check would inspect ~/.Trash ACL; but
-      #          it's easier to just check if macOS or not, and assume.
-      if ! os_is_macos; then
-        command mv -- "${trash_path}" "${to_be_deleted}"
-        command touch -- "${to_be_deleted}"
-        command mkdir -- "${trash_path}"
+      if ${trash_is_deletable} && ${rotate_is_deletable}; then
+        ${DRY_RUN} command mv -- "${first_path}" "${final_path}"
+        ${DRY_RUN} command touch -- "${final_path}"
+        ${DRY_RUN} command mkdir -p -- "${first_path}"
       else
         # SAVVY: Because ACL, cannot delete (or rename) ~/.Trash
-        #   @macOS $ /bin/ls -led ~/.Trash
-        #   drwx------+ 2 user  staff  64 May 26 13:10 /Users/user/.Trash
-        #   0: group:everyone deny delete
-
-        command mkdir -- "${to_be_deleted}"
-        command chmod 700 "${to_be_deleted}"
-
+        # This `mkdir` unnecessary but just to be clear.
+        ${DRY_RUN} command mkdir -p -- "${final_path}"
         # BWARE: Note the mv'ing ".*" includes "." and "..", which
         # generates warnings, e.g., on Linux:
         #   $ command mv -- foo/* foo/.* bar
@@ -120,12 +254,16 @@ rm_rotate () {
         #     local old_dot_glob
         #     old_dot_glob="$(shopt -p dotglob)"
         #     shopt -s dotglob
-        #     command mv -- "${trash_path}"/* "${to_be_deleted}"
+        #     command mv -- "${first_path}"/* "${final_path}"
         #     eval "${old_dot_glob}"
         # - Better yet, for POSIX compatibility, use `find`:
-        find "${trash_path}" -mindepth 1 -maxdepth 1 -name "*" \
-          -exec $(mv_kludge) -t "${to_be_deleted}" {} \+
+        ${DRY_RUN} \
+        find "${first_path}" -mindepth 1 -maxdepth 1 -name "*" \
+          -exec $(mv_kludge) -t "${final_path}" {} \+
       fi
+
+      command chmod 700 "${first_path}"
+      command chmod 700 "${final_path}"
     fi
   }
 
@@ -135,7 +273,7 @@ rm_rotate () {
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 first_char_capped () {
-  printf "$1" | cut -c1-1 | tr '[:lower:]' '[:upper:]'
+  printf "$1" | cut -c1-1 | tr "[:lower:]" "[:upper:]"
 }
 
 mv_kludge () {
@@ -193,6 +331,8 @@ main () {
   set -e
 
   set_traps
+
+  set_environs
 
   rm_rotate "$@"
 
diff --git a/deps/sh-rm_safe/bin/rm_safe b/deps/sh-rm_safe/bin/rm_safe
--- a/deps/sh-rm_safe/bin/rm_safe
+++ b/deps/sh-rm_safe/bin/rm_safe
@@ -7,7 +7,19 @@ RM_SAFE_TRASH_HOME="${RM_SAFE_TRASH_HOME:-${HOME}}"
 
 # ***
 
-RM_SAFE_TRASH_NAME=".trash"
+# USYNC: In lieu of sourcing a common lib file, keep
+#        the RM_SAFE_FIRST_TRASH environ synced. See:
+#           ~/.kit/sh/sh-rm_safe/bin/rm_safe
+#           ~/.kit/sh/sh-rm_safe/bin/rm_rotate
+set_environs () {
+  if ! os_is_macos; then
+    RM_SAFE_FIRST_TRASH="${RM_SAFE_FIRST_TRASH:-.trash0}"
+    # RM_SAFE_FINAL_TRASH="${RM_SAFE_FINAL_TRASH:-.trash}"
+  else
+    RM_SAFE_FIRST_TRASH="${RM_SAFE_FIRST_TRASH:-.Trash0}"
+    # RM_SAFE_FINAL_TRASH="${RM_SAFE_FINAL_TRASH:-.Trash}"
+  fi
+}
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
@@ -32,7 +44,7 @@ source_deps () {
       # NOTE: `dash` complains if missing './'.
       . "${path}"
     else
-      local depstxt=''
+      local depstxt=""
       [ "${prfx}" != "." ] && depstxt="in ‘${prfx}/${depd}’ or "
       >&2 echo "MISSING: ‘${file}’ not found ${depstxt}on PATH."
       depsnok=true
@@ -90,8 +102,8 @@ _sh_rm_safe_device_filepath_for_path () {
 _sh_rm_safe_device_filepath_for_path_file () {
   local file="$1"
 
-  local device_path=''
-  local usage_report=''
+  local device_path=""
+  local usage_report=""
 
   # NOTE: We could use awk to get the second line of output, e.g.,
   #   usage_report=$(/bin/df -T "$1")
@@ -113,7 +125,7 @@ _sh_rm_safe_device_filepath_for_path_file () {
     # Linux df (without -T):
     #   device_path="$(echo "${usage_report}" | tr -s ' ' | cut -d ' ' -f6)"
     # Linux- and macOS-compatible:
-    device_path="$(echo "${usage_report}" | tr -s ' ' | rev | cut -d' ' -f1 | rev)"
+    device_path="$(echo "${usage_report}" | tr -s " " | rev | cut -d" " -f1 | rev)"
     _trace "usage_report=${usage_report}"
   else
     # 2020-08-25: Does this happen only on ${file} not found? (lb): I think so.
@@ -159,8 +171,8 @@ _sh_rm_safe_ensure_trashdir () {
     #   happen? This smells like a DEV issue, not the user's.
     # - Note that RM_SAFE_TRASH_HOME must be nonempty, so not here for that
     #   reason.
-    >&2 echo 'rm_safe: (DEV) ERROR: No $TRASH_FS_MOUNT (‘’) determined, what gives?'
-  elif [ -f "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}" ]; then
+    >&2 echo "rm_safe: (DEV) ERROR: No $TRASH_FS_MOUNT (‘’) determined, what gives?"
+  elif [ -f "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}" ]; then
     ensured=2  # So caller invokes `rm -i`.
 
     # Similar too Bash v4+ associate array:
@@ -173,7 +185,7 @@ _sh_rm_safe_ensure_trashdir () {
       eval "previously_printed_trash_disabled_notice${fs_of_item}='1'"
     fi
   else
-    if [ ! -e "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}" ]; then
+    if [ ! -e "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}" ]; then
       ensured=0
       # 2022-02-14: Choose your poison:
       #  _sh_rm_safe_prompt_missing_trashdir_options_v1 "${fs_of_item}" \
@@ -183,7 +195,7 @@ _sh_rm_safe_ensure_trashdir () {
         || ensured=$?  # For return values, see #ensured_legend
     fi
 
-    if [ -d "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}" ]; then
+    if [ -d "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}" ]; then
       ensured=4  # So caller proceeds normally (and removes item to trash).
     fi
   fi
@@ -199,9 +211,9 @@ _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
   local ensured=0
 
   # v1 preso option.
-  local echo_boxy=true
+  local echo_boxy=${RM_SAFE_ECHO_BOXY:-true}
 
-  >&2 printf '%b\n' \
+  >&2 printf "%b\n" \
     "No root-level trash found for device ‘$(fg_lavender)${fs_of_item}$(attr_reset)’"
 
   local sudo_prefix=""
@@ -215,7 +227,7 @@ _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
     # - Note this is not the case that the user has encrypted the
     #   entire drive. Just their home directory.
     >&2 echo
-    >&2 echo "No root trash directory ‘/${RM_SAFE_TRASH_NAME}’ found on root device ‘/’"
+    >&2 echo "No root trash directory ‘/${RM_SAFE_FIRST_TRASH}’ found on root device ‘/’"
     >&2 echo
     >&2 echo "- Possibly because your home is encrypted, good job!"
     >&2 echo
@@ -224,20 +236,20 @@ _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
 
     # <Sigh> Technically this works, because `local` variables from parent
     # are visible/settable from child functions. But it still feels weird.
-    TRASH_FS_MOUNT=''
+    TRASH_FS_MOUNT=""
   fi
 
   if ${echo_boxy}; then
-    printf '%s\n' "┌──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┐"
-    printf '%s\n' "│ Create new trash at ‘${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}’ ?   │"
-    printf '%s'   "│ Create trash? [y/N]:              ${TRASH_FS_MOUNT//?/ }│"
-    printf '\r'
-    printf '%s'   "│ Create trash? [y/N]: "
+    printf "%s\n" "┌──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┐"
+    printf "%s\n" "│ Create new trash at ‘${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}’ ?   │"
+    printf "%s"   "│ Create trash? [y/N]:              ${TRASH_FS_MOUNT//?/ }│"
+    printf "\r"
+    printf "%s"   "│ Create trash? [y/N]: "
   else
-    >&2 printf '%b\n' \
-      "- HINT: To skip this ask: $(fg_lavender)touch ${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}$(attr_reset)"
-    printf '%b' \
-      "rm_safe: create a new trash at ‘$(fg_lavender)${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}$(attr_reset)’? [y/N] "
+    >&2 printf "%b\n" \
+      "- HINT: To skip this ask: $(fg_lavender)touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)"
+    printf "%b" \
+      "rm_safe: create a new trash at ‘$(fg_lavender)${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)’? [y/N] "
   fi
 
   read the_choice
@@ -246,16 +258,16 @@ _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
     ensured=3  # So caller asks to move to home-trash; or invokes `rm -i`.
     if ${echo_boxy}; then
       >&2 echo "│ HINT: To disable this ask:        ${TRASH_FS_MOUNT//?/ }│"
-      >&2 echo "│          touch ${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}            │"
+      >&2 echo "│          touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}            │"
       >&2 echo "└──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┘"
     fi
   else
     # Parent sets ensured=4 in a later [ -d ].
-    ${sudo_prefix} mkdir -p "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}"
+    ${sudo_prefix} mkdir -p -- "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}"
 
     if [ -n "${sudo_prefix}" ]; then
-      sudo chgrp staff "/${RM_SAFE_TRASH_NAME}"
-      sudo chmod 2775 "/${RM_SAFE_TRASH_NAME}"
+      sudo chgrp staff "/${RM_SAFE_FIRST_TRASH}"
+      sudo chmod 2775 "/${RM_SAFE_FIRST_TRASH}"
     fi
   fi
 
@@ -267,17 +279,20 @@ _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
 _sh_rm_safe_prompt_missing_trashdir_options_v1_prompt_home_trash () {
   local trash_fs_mount="$1"
 
+  # v1 preso option.
+  local echo_boxy=${RM_SAFE_ECHO_BOXY:-true}
+
   local ensured=3
 
   if ${echo_boxy}; then
-    printf '%s\n' "┌────────────────────────${trash_fs_mount//?/─}───────────┐"
-    printf '%s\n' "│ Move to main trash at ‘${trash_fs_mount}/${RM_SAFE_TRASH_NAME}’ ? │"
-    printf '%s'   "│ Move item? [y/N]:                 ${trash_fs_mount//?/ }│"
-    printf '\r'
-    printf '%s'   "│ Move item? [y/N]: "
+    printf "%s\n" "┌────────────────────────${trash_fs_mount//?/─}───────────┐"
+    printf "%s\n" "│ Move to main trash at ‘${trash_fs_mount}/${RM_SAFE_FIRST_TRASH}’ ? │"
+    printf "%s"   "│ Move item? [y/N]:                 ${trash_fs_mount//?/ }│"
+    printf "\r"
+    printf "%s"   "│ Move item? [y/N]: "
   else
-    printf '%b' \
-      "rm_safe: move item to trash at ‘$(fg_lavender)${trash_fs_mount}/${RM_SAFE_TRASH_NAME}$(attr_reset)’? [y/N] "
+    printf "%b" \
+      "rm_safe: move item to trash at ‘$(fg_lavender)${trash_fs_mount}/${RM_SAFE_FIRST_TRASH}$(attr_reset)’? [y/N] "
   fi
 
   read the_choice
@@ -318,7 +333,7 @@ _sh_rm_safe_prompt_missing_trashdir_options_v2 () {
 
   # For return values, see #ensured_legend
   local ensured=0
-  _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react \
+  _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react "${nitems_to_go}" \
     || ensured=$?
 
   PREVIOUSLY_PRINTED_MISSING_TRASHDIR_PROMPT=true
@@ -361,14 +376,14 @@ _sh_rm_safe_verify_non_root_trash_fs_mount () {
 _sh_rm_safe_prompt_missing_trashdir_print_notice () {
   local fs_of_item="$1"
 
-  >&2 printf '%b\n' \
+  >&2 printf "%b\n" \
     "NOTICE: There's no device trash for ‘$(fg_lavender)${fs_of_item}$(attr_reset)’"
 }
 
 _sh_rm_safe_prompt_missing_trashdir_print_header () {
   local item_path="$1"
 
-  # SYNC_ME: There are 66 spaces between "‘${item_path}’" and "│" if item_path=''.
+  # SYNC_ME: There are 66 spaces between "‘${item_path}’" and "│" if item_path="".
   let "ftype_nspaces = 66 - ${#item_path}"
   local ftype_postfix=""
   # Only print "│"  if we're padding, otherwise let path extend past right pipe boundary.
@@ -394,6 +409,10 @@ _sh_rm_safe_prompt_missing_trashdir_print_header () {
 _sh_rm_safe_prompt_missing_trashdir_print_options () {
   local trash_fs_mount="$1"
   local nitems_to_go="$2"
+
+  local device_trash="${trash_fs_mount}/${RM_SAFE_FIRST_TRASH}"
+
+  local main_trash="${RM_SAFE_TRASH_HOME}/${RM_SAFE_FIRST_TRASH}"
 
   # ***
 
@@ -422,11 +441,10 @@ _sh_rm_safe_prompt_missing_trashdir_print_options () {
 
   # ***
 
-  local device_trash="${trash_fs_mount}/${RM_SAFE_TRASH_NAME}"
-
-  # SYNC_ME: There are 59 spaces between "‘${device_trash}’" and "│" if device_trash=''.
+  # SYNC_ME: There are 59 spaces between "‘${device_trash}’" and "│" if device_trash="".
   # - E.g.,
   #     │          ‘’                                                           │
+  #                  12345678901234567890123456789012345678901234567890123456789
   let "device_trash_nspaces = 59 - ${#device_trash}"
   local device_trash_postfis=""
   # Only print "│"  if we're padding, otherwise let path extend past right pipe boundary.
@@ -439,8 +457,6 @@ _sh_rm_safe_prompt_missing_trashdir_print_options () {
 
   # ***
 
-  local main_trash="${RM_SAFE_TRASH_HOME}/${RM_SAFE_TRASH_NAME}"
-
   # SYNC_ME: There are 59 spaces between "‘${main_trash}’" and "│" if main_trash=''.
   # - E.g.,
   #     │          ‘’                                                           │
@@ -452,6 +468,15 @@ _sh_rm_safe_prompt_missing_trashdir_print_options () {
     # CRUMB: Same outcome as another repeat character trick:
     #  let "main_trash_nspaces = 66 - ${#main_trash} + 1"  # Add one for '│'
     #  main_trash_postfis="$(eval "printf '%*s' ${main_trash_nspaces} '│'")"
+  fi
+
+  # ***
+
+  local will_create_main_trash=""
+  if [ "$(realpath -- "${device_trash}")" = "$(realpath -- "${main_trash}")" ]; then
+    will_create_main_trash="\
+│                                                                       │
+│       ** Note this will create the trash directory                    │"
   fi
 
   # ***
@@ -470,6 +495,7 @@ ${text_move_all_items_to_new_trash}
 ${text_move_this_item_to_main_trash}
 │          ‘${main_trash}’${main_trash_postfis}\
 ${option_send_all_to_main_trash}
+${will_create_main_trash}
 │                                                                       │
 │ ► ↳   [<Enter>] is the same as [m]: use main trash for current item   │
 │                                                                       │
@@ -490,18 +516,24 @@ ${option_obliterate_all_items}
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
 _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
+  local nitems_to_go="$1"
+
   read the_choice
 
-  local device_trash="${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}"
+  local device_trash="${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}"
+
+  local main_trash="${RM_SAFE_TRASH_HOME}/${RM_SAFE_FIRST_TRASH}"
 
   # For return values, see #ensured_legend
   if [ "${the_choice}" = "d" ]; then
-    mkdir -p "${device_trash}"
+    mkdir -p -- "${device_trash}"
 
     return 4  # All set! Tell caller to use ${TRASH_FS_MOUNT}/.trash.
   fi
 
   if [ "${the_choice}" = "m" ] || [ "${the_choice}" = "" ]; then
+    mkdir -p -- "${main_trash}"
+
     # <Sigh> Technically this works, because `local` variables from parent
     # are visible/settable from child functions. But it still feels weird.
     TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
@@ -509,11 +541,13 @@ _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
     return 4  # All set! Tell caller to use ${TRASH_FS_MOUNT}/.trash.
   fi
 
-  if [ "${the_choice}" = "a" ]; then
-    TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
-    TRASH_FS_MOUNT_LOCKED=true
+  if [ ${nitems_to_go} -gt 0 ]; then
+    if [ "${the_choice}" = "a" ]; then
+      TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
+      TRASH_FS_MOUNT_LOCKED=true
 
-    return 4  # All set!
+      return 4  # All set!
+    fi
   fi
 
   if [ "${the_choice}" = "r" ]; then
@@ -524,14 +558,16 @@ _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
     return 22  # Call destructive `rm -rf` on current item.
   fi
 
-  if [ "${the_choice}" = "Ra" ]; then
-    return 32  # Call very destructive `rm -rf` on current and remaining items.
+  if [ ${nitems_to_go} -gt 0 ]; then
+    if [ "${the_choice}" = "Ra" ]; then
+      return 32  # Call very destructive `rm -rf` on current and remaining items.
+    fi
   fi
 
   if [ "${the_choice}" = "h" ]; then
     _sh_rm_safe_print_missing_trash_fs_mount_hint "${device_trash}"
 
-    return 1  # Printing hints when ask feels like a we're-done moment.
+    return 1
   fi
 }
 
@@ -540,7 +576,7 @@ _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
 _sh_rm_safe_print_missing_trash_fs_mount_hint () {
   local device_trash="$1"
 
-  local main_trash="${RM_SAFE_TRASH_HOME}/${RM_SAFE_TRASH_NAME}"
+  local main_trash="${RM_SAFE_TRASH_HOME}/${RM_SAFE_FIRST_TRASH}"
 
   local hint="
 ┌───────────────────────────────────────────────────────────────────────┐
@@ -549,7 +585,7 @@ _sh_rm_safe_print_missing_trash_fs_mount_hint () {
 
 - 1.) To always use a local device trash, choose 'd' or run:
 
-        mkdir \"${device_trash}\"
+        mkdir -- \"${device_trash}\"
 
 - 2.) To always ignore trash and call \`rm -i\`:
 
@@ -620,21 +656,25 @@ _sh_rm_safe_process_items () {
     # ensured=4 means the trash directory is prepared; move 'deleted' files there.
     local fname=${bname}
 
-    if [ -e "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}/${fname}" ] || \
-       [ -h "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}/${fname}" ]; \
+    if [ -e "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}/${fname}" ] || \
+       [ -h "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}/${fname}" ]; \
     then
       # Add a UUID fragment to generate a unique name.
       fname="${bname}.$(date +%Y_%m_%d_%Hh%Mm%Ss)-$(uuidgen | head -c8)"
     fi
 
+    _trace "command mv ${arg_verbose} -- \\
+      \"$(dirname -- "${item_path}")/${bname}\" \\
+      \"${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}/${fname}\""
+
     # If item_path is a symlink and includes a trailing slash, doing a raw mv:
-    #  command mv ${arg_verbose} -- "${item_path}" "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}/${fname}"
+    #  command mv ${arg_verbose} -- "${item_path}" "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}/${fname}"
     # causes a response like:
     #   mv: cannot move ‘symlink/’ to
     #    ‘/path/to/.trash/symlink.2015_12_03_14h26m51s_179228194’: Not a directory
     command mv ${arg_verbose} -- \
       "$(dirname -- "${item_path}")/${bname}" \
-      "${TRASH_FS_MOUNT}/${RM_SAFE_TRASH_NAME}/${fname}"
+      "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}/${fname}"
   fi
 
   [ ${ensured} -ne 1 ] || return ${ensured}
@@ -896,7 +936,7 @@ rm_safe () {
   if [ -z "${RM_SAFE_TRASH_HOME}" ]; then
     # We set RM_SAFE_TRASH_HOME in this file, so if here, DEV's fault.
     # - Note we don't allow empty string, either.
-    >&2 echo 'rm_safe: No $RM_SAFE_TRASH_HOME (‘’), what gives?'
+    >&2 echo "rm_safe: No \$RM_SAFE_TRASH_HOME (‘’), what gives?"
 
     return 1
   fi
@@ -915,7 +955,7 @@ rm_safe () {
 # The trash can way!
 # You can disable the trash by running
 #   command rm -rf ~/.trash && touch ~/.trash
-# You can make the trash with `rmtrash` or `mkdir ~/.trash`,
+# You can make the trash with `mkdir ~/.trash`,
 # or run the `rm_safe` command and you'll be prompted.
 
 rm_safe_run () {
@@ -946,7 +986,7 @@ rm_safe_run () {
       || true
 
     local bname=$(basename -- "${item_path}")
-    if [ "${bname}" = '.' ] || [ "${bname}" = '..' ]; then
+    if [ "${bname}" = "." ] || [ "${bname}" = ".." ]; then
       continue
     fi
 
@@ -1063,6 +1103,12 @@ set_trash_fs_mount () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+os_is_macos () {
+  [ "$(uname)" = "Darwin" ]
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
 clear_traps () {
   trap - EXIT INT
 }
@@ -1106,6 +1152,8 @@ main () {
   set -e
 
   set_traps
+
+  set_environs
 
   rm_safe "$@"
 
