Deps: Update faithfuls <sh-rm_safe>
- Source: sh-rm_safe @ 7e3a7a0a07f0 [1.2.0 at HEAD~4 “fcaeb61”]

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/DepoXy/depoxy/blob/release/home/.kit/git/ohmyrepos/lib/my-deps-manage-shoilerplate.sh

diff --git a/deps/sh-rm_safe/bin/rm_safe b/deps/sh-rm_safe/bin/rm_safe
--- a/deps/sh-rm_safe/bin/rm_safe
+++ b/deps/sh-rm_safe/bin/rm_safe
@@ -155,6 +155,18 @@ _sh_rm_safe_device_filepath_for_path_file () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+#  1: Stop processing (and return nonzero) (b/c DEV error (unrecoverable))
+RMSAFE_ENSURED_ERROR=1
+#  2: Call safe `rm` [rm -i ] on curr item (b/c user chose <r>).
+RMSAFE_ENSURED_CONFIRM=2
+# 22: Call mean `rm` [rm -rf] on curr item (b/c user chose <R>).
+RMSAFE_ENSURED_FORCE_ONE=22
+# 32: Call mean `rm` [rm -rf] on all items (b/c user chose <Ra>).
+RMSAFE_ENSURED_FORCE_ALL=32
+#  4: All set! Remove curr item to path specified by ${TRASH_FS_MOUNT}
+#     (which is either device-local or user-home trash).
+RMSAFE_ENSURED_TRASH_BIN=4
+
 _sh_rm_safe_ensure_trashdir () {
   local fs_of_item="$1"
   local item_path="$2"
@@ -163,7 +175,8 @@ _sh_rm_safe_ensure_trashdir () {
   local ensured=0
 
   if [ -z "${TRASH_FS_MOUNT}" ]; then
-    ensured=1  # So caller stops processing and returns error.
+    # So caller stops processing and returns error.
+    ensured=${RMSAFE_ENSURED_ERROR:-1}
 
     # This branch happens if _sh_rm_safe_device_filepath_for_path does not
     # find (echo) a device path.
@@ -173,14 +186,15 @@ _sh_rm_safe_ensure_trashdir () {
     #   reason.
     >&2 echo "rm_safe: (DEV) ERROR: No $TRASH_FS_MOUNT (‘’) determined, what gives?"
   elif [ -f "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}" ]; then
-    ensured=2  # So caller invokes `rm -i`.
+    # So caller invokes `rm -i`
+    ensured=${RMSAFE_ENSURED_CONFIRM:-2}
 
     # Similar too Bash v4+ associate array:
     #   if [ -z "${previously_printed_trash_disabled_notice[${fs_of_item}]}" ]; then
     if [ -z "$(eval echo '$'previously_printed_trash_disabled_notice${fs_of_item})" ]; then
       >&2 echo "The trash is disabled on device ‘${fs_of_item}’"
 
-      # Similar too Bash v4+ associate array:
+      # Similar to Bash v4+ associate array:
       #  previously_printed_trash_disabled_notice[${fs_of_item}]="1"
       eval "previously_printed_trash_disabled_notice${fs_of_item}='1'"
     fi
@@ -196,7 +210,8 @@ _sh_rm_safe_ensure_trashdir () {
     fi
 
     if [ -d "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}" ]; then
-      ensured=4  # So caller proceeds normally (and removes item to trash).
+      # So caller proceeds normally (and removes item to trash)
+      ensured=${RMSAFE_ENSURED_TRASH_BIN:-4}
     fi
   fi
 
@@ -205,74 +220,76 @@ _sh_rm_safe_ensure_trashdir () {
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
-_sh_rm_safe_prompt_missing_trashdir_options_v1 () {
-  local fs_of_item="$1"
-
-  local ensured=0
-
-  # v1 preso option.
-  local echo_boxy=${RM_SAFE_ECHO_BOXY:-true}
-
-  >&2 printf "%b\n" \
-    "No root-level trash found for device ‘$(fg_lavender)${fs_of_item}$(attr_reset)’"
-
-  local sudo_prefix=""
-
-  if [ "${TRASH_FS_MOUNT}" = "/" ]; then
-    # The file being deleted lives on the root device but the default
-    # trash directory is not on the same device. This could mean the
-    # user has an encrypted home directory. Rather than moving files
-    # to the encrypted space, use an unencrypted trash location, but
-    # make the user do it.
-    # - Note this is not the case that the user has encrypted the
-    #   entire drive. Just their home directory.
-    >&2 echo
-    >&2 echo "No root trash directory ‘/${RM_SAFE_FIRST_TRASH}’ found on root device ‘/’"
-    >&2 echo
-    >&2 echo "- Possibly because your home is encrypted, good job!"
-    >&2 echo
-
-    sudo_prefix="sudo"
-
-    # <Sigh> Technically this works, because `local` variables from parent
-    # are visible/settable from child functions. But it still feels weird.
-    TRASH_FS_MOUNT=""
-  fi
-
-  if ${echo_boxy}; then
-    printf "%s\n" "┌──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┐"
-    printf "%s\n" "│ Create new trash at ‘${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}’ ?   │"
-    printf "%s"   "│ Create trash? [y/N]:              ${TRASH_FS_MOUNT//?/ }│"
-    printf "\r"
-    printf "%s"   "│ Create trash? [y/N]: "
-  else
-    >&2 printf "%b\n" \
-      "- HINT: To skip this ask: $(fg_lavender)touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)"
-    printf "%b" \
-      "rm_safe: create a new trash at ‘$(fg_lavender)${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)’? [y/N] "
-  fi
-
-  read the_choice
-
-  if [ "${the_choice}" != "y" ] && [ "${the_choice}" != "Y" ]; then
-    ensured=3  # So caller asks to move to home-trash; or invokes `rm -i`.
-    if ${echo_boxy}; then
-      >&2 echo "│ HINT: To disable this ask:        ${TRASH_FS_MOUNT//?/ }│"
-      >&2 echo "│          touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}            │"
-      >&2 echo "└──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┘"
-    fi
-  else
-    # Parent sets ensured=4 in a later [ -d ].
-    ${sudo_prefix} mkdir -p -- "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}"
-
-    if [ -n "${sudo_prefix}" ]; then
-      sudo chgrp staff "/${RM_SAFE_FIRST_TRASH}"
-      sudo chmod 2775 "/${RM_SAFE_FIRST_TRASH}"
-    fi
-  fi
-
-  return ${ensured}
-}
+# ISOFF/2024-07-14: Old v1 flow:
+#
+#   _sh_rm_safe_prompt_missing_trashdir_options_v1 () {
+#     local fs_of_item="$1"
+#
+#     local ensured=0
+#
+#     # v1 preso option.
+#     local echo_boxy=${RM_SAFE_ECHO_BOXY:-true}
+#
+#     >&2 printf "%b\n" \
+#       "No root-level trash found for device ‘$(fg_lavender)${fs_of_item}$(attr_reset)’"
+#
+#     local sudo_prefix=""
+#
+#     if [ "${TRASH_FS_MOUNT}" = "/" ]; then
+#       # The file being deleted lives on the root device but the default
+#       # trash directory is not on the same device. This could mean the
+#       # user has an encrypted home directory. Rather than moving files
+#       # to the encrypted space, use an unencrypted trash location, but
+#       # make the user do it.
+#       # - Note this is not the case that the user has encrypted the
+#       #   entire drive. Just their home directory.
+#       >&2 echo
+#       >&2 echo "No root trash directory ‘/${RM_SAFE_FIRST_TRASH}’ found on root device ‘/’"
+#       >&2 echo
+#       >&2 echo "- Possibly because your home is encrypted, good job!"
+#       >&2 echo
+#
+#       sudo_prefix="sudo"
+#
+#       # <Sigh> Technically this works, because `local` variables from parent
+#       # are visible/settable from child functions. But it still feels weird.
+#       TRASH_FS_MOUNT=""
+#     fi
+#
+#     if ${echo_boxy}; then
+#       printf "%s\n" "┌──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┐"
+#       printf "%s\n" "│ Create new trash at ‘${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}’ ?   │"
+#       printf "%s"   "│ Create trash? [y/N]:              ${TRASH_FS_MOUNT//?/ }│"
+#       printf "\r"
+#       printf "%s"   "│ Create trash? [y/N]: "
+#     else
+#       >&2 printf "%b\n" \
+#         "- HINT: To skip this ask: $(fg_lavender)touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)"
+#       printf "%b" \
+#         "rm_safe: create a new trash at ‘$(fg_lavender)${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}$(attr_reset)’? [y/N] "
+#     fi
+#
+#     read the_choice
+#
+#     if [ "${the_choice}" != "y" ] && [ "${the_choice}" != "Y" ]; then
+#       ensured=3  # So caller asks to move to home-trash; or invokes `rm -i`.
+#       if ${echo_boxy}; then
+#         >&2 echo "│ HINT: To disable this ask:        ${TRASH_FS_MOUNT//?/ }│"
+#         >&2 echo "│          touch ${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}            │"
+#         >&2 echo "└──────────────────────${TRASH_FS_MOUNT//?/─}─────────────┘"
+#       fi
+#     else
+#       # Parent sets ensured=4 in a later [ -d ].
+#       ${sudo_prefix} mkdir -p -- "${TRASH_FS_MOUNT}/${RM_SAFE_FIRST_TRASH}"
+#
+#       if [ -n "${sudo_prefix}" ]; then
+#         sudo chgrp staff "/${RM_SAFE_FIRST_TRASH}"
+#         sudo chmod 2775 "/${RM_SAFE_FIRST_TRASH}"
+#       fi
+#     fi
+#
+#     return ${ensured}
+#   }
 
 # ***
 
@@ -526,19 +543,20 @@ _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
 
   # For return values, see #ensured_legend
   if [ "${the_choice}" = "d" ]; then
-    mkdir -p -- "${device_trash}"
+    _sh_rm_safe_ensure_trash_dir_with_proper_permissions "${device_trash}"
 
     return 4  # All set! Tell caller to use ${TRASH_FS_MOUNT}/.trash.
   fi
 
   if [ "${the_choice}" = "m" ] || [ "${the_choice}" = "" ]; then
-    mkdir -p -- "${main_trash}"
+    _sh_rm_safe_ensure_trash_dir_with_proper_permissions "${main_trash}"
 
     # <Sigh> Technically this works, because `local` variables from parent
     # are visible/settable from child functions. But it still feels weird.
     TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
 
-    return 4  # All set! Tell caller to use ${TRASH_FS_MOUNT}/.trash.
+    # All set! Tell caller to use ${TRASH_FS_MOUNT}/.trash.
+    return ${RMSAFE_ENSURED_TRASH_BIN:-4}
   fi
 
   if [ ${nitems_to_go} -gt 0 ]; then
@@ -546,28 +564,49 @@ _sh_rm_safe_prompt_missing_trashdir_read_choice_and_react () {
       TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
       TRASH_FS_MOUNT_LOCKED=true
 
-      return 4  # All set!
+      # All set!
+      return ${RMSAFE_ENSURED_TRASH_BIN:-4}
     fi
   fi
 
   if [ "${the_choice}" = "r" ]; then
-    return 2  # Call gentle `rm -i` on current item.
+    # Call gentle `rm -i` on current item.
+    return ${RMSAFE_ENSURED_CONFIRM:-2}
   fi
 
   if [ "${the_choice}" = "R" ]; then
-    return 22  # Call destructive `rm -rf` on current item.
+    # Call destructive `rm -rf` on current item.
+    return ${RMSAFE_ENSURED_FORCE_ONE:-22}
   fi
 
   if [ ${nitems_to_go} -gt 0 ]; then
     if [ "${the_choice}" = "Ra" ]; then
-      return 32  # Call very destructive `rm -rf` on current and remaining items.
+      # Call very destructive `rm -rf` on current and remaining items.
+      return ${RMSAFE_ENSURED_FORCE_ALL:-32}
     fi
   fi
 
   if [ "${the_choice}" = "h" ]; then
     _sh_rm_safe_print_missing_trash_fs_mount_hint "${device_trash}"
 
-    return 1
+    return ${RMSAFE_ENSURED_ERROR:-1}
+  fi
+}
+
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
+
+# USYNC: See same-named fcn. in rm_rotate
+_sh_rm_safe_ensure_trash_dir_with_proper_permissions () {
+  local trash_dir="$1"
+
+  command mkdir -p -- "${trash_dir}"
+
+  command chmod 700 "${trash_dir}"
+
+  if os_is_macos; then
+    # Ensure ~/.Trash0 permissions like ~/.Trash
+    # - Though perhaps to 
+    command chmod +a "group:everyone deny delete" "${trash_dir}"
   fi
 }
 
@@ -630,29 +669,33 @@ _sh_rm_safe_process_items () {
   _sh_rm_safe_ensure_trashdir "${fs_of_item}" "${item_path}" "${nitems_to_go}" \
     || ensured=$?
 
-  if [ ${ensured} -eq 3 ]; then
-    # Ask if user wants to move file to home-trash instead.
-    TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
+  # ISOFF/2024-07-14: Old v1 flow:
+  #
+  #   if [ ${ensured} -eq 3 ]; then
+  #     # Ask if user wants to move file to home-trash instead.
+  #     TRASH_FS_MOUNT="${RM_SAFE_TRASH_HOME}"
+  #
+  #     ensured=0
+  #     _sh_rm_safe_prompt_missing_trashdir_options_v1_prompt_home_trash "${TRASH_FS_MOUNT}" \
+  #       || ensured=$?
+  #   fi
 
-    ensured=0
-    _sh_rm_safe_prompt_missing_trashdir_options_v1_prompt_home_trash "${TRASH_FS_MOUNT}" \
-      || ensured=$?
-  fi
-
-  if [ ${ensured} -eq 2 ]; then
+  if [ ${ensured} -eq ${RMSAFE_ENSURED_CONFIRM:-2} ]; then
     # User specifically not using safety trash on this device; or for this file.
     command rm -i ${arg_verbose} -- "${item_path}"
-  elif [ ${ensured} -eq 22 ] || [ ${ensured} -eq 32 ]; then
+  elif [ ${ensured} -eq ${RMSAFE_ENSURED_FORCE_ONE:-22} ] \
+    || [ ${ensured} -eq ${RMSAFE_ENSURED_FORCE_ALL:-32} ] \
+  ; then
     command rm -rf ${arg_verbose} -- "${item_path}"
 
     # We already printed a prompt. Might as well print a confirmation?
     echo
     >&2 echo "rm_safe: Removed ‘${item_path}’"
 
-    if [ ${ensured} -eq 32 ]; then
+    if [ ${ensured} -eq ${RMSAFE_ENSURED_FORCE_ALL:-32} ]; then
       ARG_RECURSIVE_FORCE=true
     fi
-  elif [ ${ensured} -eq 4 ]; then
+  elif [ ${ensured} -eq ${RMSAFE_ENSURED_TRASH_BIN:-4} ]; then
     # ensured=4 means the trash directory is prepared; move 'deleted' files there.
     local fname=${bname}
 
